### ISSUE TITLE
Cython error when following macports install instructions

### ISSUE THREAD

**Issue by stargaser** [astrofrog/macports-python#1]
Hi, I've followed the instructions for MacPorts and got everything to install except for the two ascii table packages, py27-asciitable and py27-atpy.  There is a checksum error in py27-cython.  This is a known issue as it is described here: https://trac.macports.org/ticket/28682

I'm afraid I don't understand how to work around this. Aside from this issue, the install went exceptionally smoothly and quickly (less than 90 minutes).

Best regards,
David Shupe

**Comment by astrofrog** [comment]
Thanks for reporting the issues - I'll look into them! What was the error with py27-atpy and py27-asciitable?

**Comment by astrofrog** [comment]
I have fixed the Cython issue in Macports, so try:

```
sudo port selfupdate
```

then try installing Cython again. Could you let me know what issues you had with asciitable and atpy?

**Comment by stargaser** [comment]
Thanks!  I'll try this as soon as I'm back at my desktop later today. 

There wasn't an issue with atpy and asciitable themselves. They both require Cython so the install failed at that step.

**Comment by astrofrog** [comment]
That makes sense - atpy requires h5py which requires cython. I think that asciitable must have been listed to be installed after atpy, but it doesn't require cython. Anyway, please report back once you've had a chance to try this so I know whether to close the ticket.

**Comment by stargaser** [comment]
I tried the "sudo port selfupdate", then the install of py27-atpy, and it worked!  Thanks!

You are right about asciitable -- it did install correctly, just before the cython install failed.  I didn't read the terminal messages carefully the first time -- sorry about that.

If I may ask another question before this issue is closed:  After the port install of cython failed the first time, I tried "/opt/local/bin/easy_install-2.7 --user -U cython" which installed Cython 0.15.  But after that, the MacPorts install of atpy still tried to install Cython.  Is this because MacPorts keeps track only of what it has installed itself, and not what has been installed by other methods into this Python distribution?

**Comment by astrofrog** [comment]
That is correct - MacPorts installs all the dependencies it needs, and will ignore what you have installed in terms of dependencies (this is to ensure there are no version issues, etc.). Thanks for reporting the Cython issue! It looks like the macports ticket hadn't been touched for a few months, so it was good to get it fixed.
