### ISSUE TITLE
Installing packages not in macports

### ISSUE THREAD

**Issue by stargaser** [astrofrog/macports-python#2]
I have a question about the section of the documentation "Installing packages not in macports".  Here it is explained how to properly use `python setup.py`.  Can't we alternatively use `easy_install`, specifically 
   /opt/local/bin/easy_install-2.7 --user -U  <pkg_name>
or is this not recommended?

**Comment by astrofrog** [comment]
You should be able to use --user with both `easy_install-2.7` and `pip-2.7`. I will update the documentation to state this.
